package com.example.keyri.ai

/**
 * Built-in English lexicon so suggestions work from first launch,
 * before any personalization has been learned.
 * Words are ordered by approximate frequency; completions respect that order.
 */
object EnglishLexicon {

    val starters = listOf("I", "Hey", "Thanks")

    val fallback = listOf("the", "and", "you")

    fun completions(partial: String, topK: Int): List<String> =
        words.asSequence()
            .filter { it.startsWith(partial) && it != partial }
            .take(topK)
            .toList()

    /**
     * Next-word combinations like a stock keyboard: the two-word context is checked
     * first ("how are" -> "you"), then single-word pairs, so common everyday phrases
     * complete naturally.
     */
    fun nextWords(previous2: String?, previous: String): List<String> {
        val fromTrigram = previous2?.let { seedTrigrams["$it $previous"] }.orEmpty()
        val fromBigram = seedBigrams[previous].orEmpty()
        return (fromTrigram + fromBigram).distinct()
    }

    private val seedTrigrams = mapOf(
        "how are" to listOf("you", "things", "we"),
        "are you" to listOf("doing", "coming", "free"),
        "what are" to listOf("you", "we", "the"),
        "what is" to listOf("the", "your", "this"),
        "do you" to listOf("want", "know", "have"),
        "can you" to listOf("please", "send", "call"),
        "could you" to listOf("please", "send", "check"),
        "if you" to listOf("want", "need", "can"),
        "when you" to listOf("get", "are", "come"),
        "you want" to listOf("to", "me", "it"),
        "want me" to listOf("to"),
        "you can" to listOf("come", "do", "call"),
        "we can" to listOf("meet", "talk", "do"),
        "i am" to listOf("on", "not", "going"),
        "i will" to listOf("be", "call", "let"),
        "i have" to listOf("a", "to", "been"),
        "i was" to listOf("just", "thinking", "going"),
        "i think" to listOf("it", "we", "you"),
        "i know" to listOf("that", "you", "it"),
        "i just" to listOf("wanted", "got", "saw"),
        "i love" to listOf("you", "it", "this"),
        "i miss" to listOf("you", "it", "them"),
        "just wanted" to listOf("to"),
        "wanted to" to listOf("know", "say", "ask"),
        "was just" to listOf("thinking", "about", "wondering"),
        "will be" to listOf("there", "late", "back"),
        "be there" to listOf("soon", "by", "at"),
        "going to" to listOf("be", "the", "get"),
        "have a" to listOf("good", "great", "nice"),
        "a good" to listOf("day", "time", "one"),
        "have to" to listOf("go", "do", "be"),
        "want to" to listOf("go", "do", "know"),
        "need to" to listOf("talk", "go", "do"),
        "would be" to listOf("great", "nice", "good"),
        "it is" to listOf("a", "not", "the"),
        "this is" to listOf("the", "a", "my"),
        "there is" to listOf("a", "no", "nothing"),
        "thank you" to listOf("so", "for", "very"),
        "you so" to listOf("much"),
        "thanks for" to listOf("the", "your", "everything"),
        "see you" to listOf("tomorrow", "soon", "there"),
        "talk to" to listOf("you", "me", "him"),
        "to you" to listOf("later", "soon", "about"),
        "let me" to listOf("know", "see", "check"),
        "me know" to listOf("when", "if", "what"),
        "on my" to listOf("way", "own", "phone"),
        "on the" to listOf("way", "phone", "other"),
        "in the" to listOf("morning", "evening", "next"),
        "at the" to listOf("moment", "same", "end"),
        "for the" to listOf("first", "update", "help"),
        "of the" to listOf("day", "week", "best"),
        "by the" to listOf("way", "time", "end"),
        "one of" to listOf("the", "my", "them"),
        "a lot" to listOf("of"),
        "lot of" to listOf("work", "time", "fun"),
        "as soon" to listOf("as"),
        "soon as" to listOf("possible", "you", "i"),
        "looking forward" to listOf("to"),
        "forward to" to listOf("it", "seeing", "meeting"),
        "get back" to listOf("to"),
        "back to" to listOf("you", "me", "work"),
        "call me" to listOf("when", "back", "later"),
        "call you" to listOf("later", "back", "tomorrow"),
        "text me" to listOf("when", "later", "back"),
        "take care" to listOf("of"),
        "sounds good" to listOf("to"),
        "happy birthday" to listOf("to"),
        "good morning" to listOf("everyone", "to", "all"),
        "good night" to listOf("everyone", "all", "to")
    )

    private val seedBigrams = mapOf(
        "i" to listOf("am", "will", "have"),
        "am" to listOf("going", "not", "so"),
        "you" to listOf("are", "can", "know"),
        "the" to listOf("best", "same", "next"),
        "to" to listOf("be", "get", "know"),
        "and" to listOf("then", "also", "the"),
        "a" to listOf("lot", "few", "good"),
        "is" to listOf("not", "the", "a"),
        "it" to listOf("is", "was", "will"),
        "in" to listOf("the", "a", "my"),
        "of" to listOf("the", "my", "this"),
        "for" to listOf("the", "you", "me"),
        "on" to listOf("the", "my", "time"),
        "my" to listOf("phone", "way", "house"),
        "we" to listOf("are", "can", "will"),
        "are" to listOf("you", "not", "we"),
        "will" to listOf("be", "not", "send"),
        "be" to listOf("there", "able", "back"),
        "have" to listOf("a", "to", "been"),
        "this" to listOf("is", "week", "time"),
        "that" to listOf("is", "was", "you"),
        "at" to listOf("the", "home", "work"),
        "not" to listOf("sure", "yet", "now"),
        "do" to listOf("you", "not", "it"),
        "can" to listOf("you", "we", "be"),
        "how" to listOf("are", "is", "much"),
        "what" to listOf("is", "are", "time"),
        "when" to listOf("is", "are", "you"),
        "where" to listOf("are", "is", "do"),
        "see" to listOf("you", "it", "the"),
        "thank" to listOf("you", "god", "everyone"),
        "thanks" to listOf("for", "a", "so"),
        "good" to listOf("morning", "night", "luck"),
        "let" to listOf("me", "us", "you"),
        "me" to listOf("know", "a", "the"),
        "know" to listOf("if", "what", "that"),
        "going" to listOf("to", "home", "well"),
        "come" to listOf("to", "back", "over"),
        "get" to listOf("the", "it", "back"),
        "got" to listOf("it", "the", "a"),
        "was" to listOf("a", "not", "the"),
        "just" to listOf("a", "got", "wanted"),
        "so" to listOf("much", "i", "that"),
        "all" to listOf("the", "of", "good"),
        "with" to listOf("the", "you", "me"),
        "your" to listOf("time", "help", "phone"),
        "our" to listOf("team", "next", "new"),
        "there" to listOf("is", "are", "was"),
        "here" to listOf("is", "are", "for"),
        "meet" to listOf("you", "me", "at"),
        "talk" to listOf("to", "later", "soon"),
        "call" to listOf("me", "you", "later"),
        "send" to listOf("me", "the", "it"),
        "about" to listOf("the", "it", "to"),
        "time" to listOf("to", "for", "is"),
        "next" to listOf("week", "time", "to"),
        "last" to listOf("night", "week", "time"),
        "submit" to listOf("the", "it", "before"),
        "due" to listOf("tomorrow", "today", "soon"),
        "love" to listOf("you", "it", "this"),
        "miss" to listOf("you", "it", "them"),
        "sounds" to listOf("good", "great", "like"),
        "looking" to listOf("forward", "for", "at"),
        "take" to listOf("care", "a", "it"),
        "feel" to listOf("free", "better", "like"),
        "right" to listOf("now", "away", "here"),
        "as" to listOf("soon", "well", "a"),
        "by" to listOf("the", "tomorrow", "then"),
        "after" to listOf("the", "work", "that"),
        "before" to listOf("the", "you", "we"),
        "okay" to listOf("with", "so", "then"),
        "sorry" to listOf("for", "about", "i"),
        "please" to listOf("let", "send", "check"),
        "happy" to listOf("birthday", "to", "for"),
        "hope" to listOf("you", "to", "it"),
        "wish" to listOf("you", "me", "all"),
        "don't" to listOf("know", "worry", "forget"),
        "i'm" to listOf("on", "not", "going"),
        "can't" to listOf("wait", "believe", "make"),
        "it's" to listOf("a", "not", "been"),
        "didn't" to listOf("know", "get", "see"),
        "that's" to listOf("great", "fine", "what"),
        "won't" to listOf("be", "take", "happen"),
        "wait" to listOf("for", "a", "until"),
        "almost" to listOf("done", "there", "ready"),
        "running" to listOf("late", "out", "behind"),
        "reached" to listOf("home", "there", "safely"),
        "leaving" to listOf("now", "soon", "in"),
        "reply" to listOf("when", "soon", "to"),
        "share" to listOf("the", "it", "your"),
        "join" to listOf("the", "us", "me"),
        "ping" to listOf("me", "you", "when")
    )

    private val words = listOf(
        "the", "be", "to", "of", "and", "a", "in", "that", "have", "I",
        "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
        "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
        "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
        "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
        "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
        "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
        "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
        "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
        "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
        "great", "where", "much", "need", "right", "too", "very", "here", "should", "still",
        "such", "being", "made", "before", "through", "same", "down", "call", "world", "school",
        "never", "last", "let", "thing", "tell", "really", "thanks", "thank", "please", "okay",
        "yes", "sure", "sorry", "hello", "morning", "night", "evening", "today", "tomorrow", "tonight",
        "yesterday", "week", "month", "weekend", "later", "soon", "early", "late", "again", "always",
        "home", "house", "phone", "message", "send", "sent", "meet", "meeting", "talk", "speak",
        "friend", "family", "team", "group", "class", "college", "exam", "test", "study", "studying",
        "assignment", "project", "report", "notes", "file", "details", "deadline", "submit", "update", "review",
        "email", "address", "number", "online", "video", "photo", "movie", "music", "game", "play",
        "watch", "read", "write", "start", "stop", "finish", "done", "doing", "going", "coming",
        "leave", "arrive", "wait", "waiting", "ready", "busy", "free", "happy", "love", "nice",
        "best", "better", "fine", "cool", "awesome", "amazing", "beautiful", "important", "interesting", "different",
        "money", "food", "lunch", "dinner", "breakfast", "coffee", "water", "weather", "rain", "travel",
        "trip", "drive", "walk", "run", "sleep", "wake", "help", "ask", "answer", "question",
        "problem", "idea", "plan", "place", "city", "office", "shop", "store", "open", "close",
        "buy", "sell", "pay", "cost", "price", "order", "book", "ticket", "train", "flight",
        "doctor", "health", "care", "feel", "feeling", "remember", "forget", "try", "trying", "check",
        "keep", "found", "find", "lost", "change", "turn", "move", "stay", "live", "life",
        "long", "short", "high", "low", "big", "small", "old", "young", "next", "near",
        "every", "each", "both", "few", "many", "more", "less", "little", "lot", "enough",
        "actually", "probably", "maybe", "definitely", "exactly", "almost", "around", "between", "during", "without",
        "together", "myself", "yourself", "someone", "something", "anything", "everything", "nothing", "everyone", "nobody",
        "minute", "hour", "second", "moment", "while", "since", "until", "already", "yet", "ago",
        "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday", "january", "march", "april"
    ).filter { it.all { ch -> ch.isLetter() || ch == '\'' } && it.first().code < 128 }
        .map { it.lowercase() }
        .distinct()
}
